"""
snapshot.py — write a human-readable SNAPSHOT.md of the current dataset state.

Run after the pipeline (process -> benchmark -> edge -> insights). The
daily-refresh workflow runs this and commits SNAPSHOT.md, so the repo always
carries a legible, up-to-date digest of the open slate and headline metrics
without anyone re-running anything or opening a CSV.

    python snapshot.py        # writes SNAPSHOT.md
"""

from datetime import datetime, timezone

import pandas as pd

import analysis_lib as A
import benchmark
import edge


def _pct(x):
    return "n/a" if x is None or pd.isna(x) else f"{float(x):.0%}"


def main():
    df = A.load()
    params = benchmark.load_params()
    res = df[df["is_closed"]].copy()
    nos = res[~res["is_yes"]]
    _, bt = edge.backtest_resolved(df, params)
    eo = edge.score_open(df, params)
    rb = dict(zip(df["slug"], df.get("resolve_by_date", pd.Series(dtype=str))))

    asof = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    L = []
    L.append("# FDA markets — latest snapshot")
    L.append("")
    L.append(f"*Auto-generated by `snapshot.py` on {asof}. Do not edit by hand; "
             "see FINDINGS.md / LIMITATIONS.md for analysis and caveats.*")
    L.append("")

    # --- dataset ---
    L.append("## Dataset")
    L.append("")
    L.append(f"- **{len(df)} drug markets** (the 1 thematic market is excluded): "
             f"{len(res)} resolved, {int((~df['is_closed']).sum())} open.")
    L.append(f"- Resolved **on time {int(res['is_yes'].sum())}/{len(res)}**; "
             f"the {len(nos)} \"No\" outcomes split "
             f"{int((nos['outcome'] == 'CRL').sum())} CRL / "
             f"{int((nos['outcome'] == 'Delay').sum())} delay.")
    L.append("")

    # --- open slate ---
    L.append("## Open markets")
    L.append("")
    L.append("| Drug | Price | Resolves by | Benchmark | Gap vs benchmark | Tradeable depth |")
    L.append("|---|---|---|---|---|---|")
    for _, r in eo.iterrows():
        fair = r["fair_price"]
        gap = r["gap_fair_minus_market"]
        fair_s = "n/a" if fair == "N/A" else _pct(fair)
        gap_s = "n/a" if gap == "N/A" else f"{float(gap):+.0%}"
        L.append(f"| {r['drug']} | {_pct(r['market_price'])} | "
                 f"{rb.get(r['slug'], '?')} | {fair_s} | {gap_s} | "
                 f"{'yes' if r['depth_ok'] else 'thin'} |")
    L.append("")
    L.append("*Benchmark is a transparent FDA base rate, not a forecast; gap is fair value minus market price. "
             "\"Resolves by\" is the contract's true deadline (a ~14-day grace past the expected PDUFA).*")
    L.append("")

    # --- headline metrics ---
    def acc(col):
        s = res[res[col].astype(str).str.lower().isin(["true", "false"])]
        k = int((s[col].astype(str).str.lower() == "true").sum())
        return f"{k}/{len(s)} ({_pct(k / len(s) if len(s) else None)})"

    brier = pd.to_numeric(res["brier_1d"], errors="coerce").mean()
    L.append("## How sharp is the crowd")
    L.append("")
    L.append(f"- Majority-side correct (anchored to the actual FDA action): "
             f"**{acc('correct_7d')}** at 7 days out, **{acc('correct_1d')}** at 1 day out.")
    L.append(f"- Mean Brier (1 day out): **{brier:.3f}**.")
    L.append(f"- Transparent base-rate benchmark vs the crowd (out-of-sample): "
             f"crowd Brier **{bt['market_brier_mean']}** vs benchmark **{bt['benchmark_brier_mean_paired']}**; "
             f"the base rate beat the crowd {bt['benchmark_beats_market']}/{bt['paired_decisive']} times. "
             "The crowd wins, i.e. the markets are roughly efficient.")
    L.append("")

    with open("SNAPSHOT.md", "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print("Wrote SNAPSHOT.md")


if __name__ == "__main__":
    main()
